# Generated by Django 3.2.3 on 2022-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ProfilePic',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
