# Generated by Django 3.2.3 on 2022-06-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_profile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
