# Generated by Django 3.2.3 on 2022-07-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0004_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfilePic',
            field=models.FileField(null=True, upload_to='profile/'),
        ),
    ]
