# Generated by Django 3.2.3 on 2022-06-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code_categories',
            options={'verbose_name_plural': 'Code Categories'},
        ),
    ]
