# Generated by Django 3.2.3 on 2022-06-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_alter_code_categories_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='Best_Offer',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='Most_Popular',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='New_Products',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='codeName',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='oldPrice',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='slug',
        ),
        migrations.AddField(
            model_name='code_categories',
            name='Best_Offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code_categories',
            name='Most_Popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code_categories',
            name='New_Products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code_categories',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
