# Generated by Django 3.2.3 on 2022-06-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0004_auto_20220623_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code_categories',
            old_name='slug',
            new_name='categoryslug',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='slug',
            new_name='Gameslug',
        ),
    ]
