# Generated by Django 3.2.3 on 2022-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0005_auto_20220623_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_categories',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='codeCategories'),
        ),
        migrations.AlterField(
            model_name='code_categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='codeCategories'),
        ),
    ]
