# Generated by Django 3.2.3 on 2022-07-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0007_delete_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_categories',
            name='price_bought_by',
            field=models.FloatField(default=0),
        ),
    ]
