# Generated by Django 3.2.3 on 2022-07-23 12:51

import categories_and_products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0008_code_categories_price_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_categories',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='codeCategories', validators=[categories_and_products.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='game',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='games', validators=[categories_and_products.validators._ext_photo]),
        ),
    ]
