# Generated by Django 3.2.3 on 2022-07-23 13:28

import categories_and_products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0009_auto_20220723_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='codeCategories', validators=[categories_and_products.validators._ext_photo]),
        ),
        migrations.AlterField(
            model_name='game',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='games', validators=[categories_and_products.validators._ext_photo]),
        ),
    ]
