# Generated by Django 3.2.3 on 2022-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0010_auto_20220723_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='games'),
        ),
    ]
