# Generated by Django 3.2.3 on 2022-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0011_alter_game_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_categories',
            name='codeCategory',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameName',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
