# Generated by Django 3.2.3 on 2022-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0012_auto_20220723_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_categories',
            name='Best_Offer',
            field=models.BooleanField(default=False, verbose_name='Best Products'),
        ),
    ]
