# Generated by Django 4.0.6 on 2022-07-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0013_alter_code_categories_best_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code_categories',
            options={'verbose_name_plural': 'Values'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
