# Generated by Django 3.2.3 on 2022-08-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0015_alter_code_categories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_categories',
            name='description',
            field=models.TextField(blank=True, default=' ', help_text='Make sure to write description for all categories to handel all your design'),
        ),
    ]
