# Generated by Django 3.2.3 on 2022-08-11 14:00

import categories_and_products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0016_alter_code_categories_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
                ('background_image', models.ImageField(blank=True, upload_to='codeCategories', validators=[categories_and_products.validators._ext_photo])),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
