# Generated by Django 3.2.3 on 2022-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0017_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_categories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='created',
        ),
        migrations.AddField(
            model_name='code_categories',
            name='instruction',
            field=models.TextField(blank=True, default=' ', help_text='Write a guide for installing the codes in the game platfrom'),
        ),
    ]
