# Generated by Django 3.2.3 on 2022-07-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0006_auto_20220624_1938'),
        ('cart_and_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='code',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.codes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='codeCategory',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.code_categories'),
            preserve_default=False,
        ),
    ]
