# Generated by Django 3.2.3 on 2022-07-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0005_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
