# Generated by Django 3.2.3 on 2022-07-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0007_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codes',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
