# Generated by Django 3.2.3 on 2022-07-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0008_auto_20220707_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryFees',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offerPercentage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_after_offer',
        ),
    ]
