# Generated by Django 3.2.3 on 2022-07-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_and_orders', '0011_cartitems_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='code',
        ),
        migrations.AddField(
            model_name='codes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
