# Generated by Django 3.2.3 on 2022-07-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0012_auto_20220712_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='addToCart',
            field=models.BooleanField(default=False),
        ),
    ]
