# Generated by Django 3.2.3 on 2022-07-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0013_codes_addtocart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='stock',
        ),
    ]
