# Generated by Django 3.2.3 on 2022-07-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0014_remove_codes_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='category',
            new_name='codeCategory',
        ),
    ]
