# Generated by Django 3.2.3 on 2022-07-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0017_remove_order_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_and_orders.order'),
        ),
    ]
