# Generated by Django 3.2.3 on 2022-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0020_codes_total_profit_calculated_from_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
