# Generated by Django 3.2.3 on 2022-07-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0021_codes_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='price_bought_by',
        ),
    ]
