# Generated by Django 3.2.3 on 2022-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0023_auto_20220723_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
