# Generated by Django 3.2.3 on 2022-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0026_auto_20220810_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_response',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_by',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
