# Generated by Django 3.2.3 on 2022-08-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0027_auto_20220810_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_after_taxes',
            field=models.FloatField(default=0, verbose_name='After Taxes'),
        ),
    ]
