# Generated by Django 3.2.3 on 2022-08-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0028_auto_20220810_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='shipped',
        ),
    ]
