# Generated by Django 3.2.3 on 2022-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0029_remove_cartitems_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending')], default=18, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codes',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending')], default=16, max_length=50),
            preserve_default=False,
        ),
    ]
